### ISSUE TITLE
Reviewer Credits

### ISSUE THREAD

**Issue by withanage** [pkp/orcidProfile#181]
#### Review functionality

https://user-images.githubusercontent.com/1921992/143842439-6bda500e-ae19-4f38-a983-5dfc9be781a3.mp4

#### Reviewer Anonymity metadata transfer concept

| Information | Orcid Field | Anonymous | Open |
| --- |  --- | --- | --- |
| 1. Date of submission | created-date | YYYY | YYYY-MM-DD |
| 2. Date of acceptance  (review)|  review-completion-date | YYYY | YYYY-MM-DD |
| 3. Date of publication  | created-date | YYYY | YYYY-MM-DD |
| 7. Article URL   | review-url | :x: | :heavy_check_mark: |
### Plugin Settings

https://user-images.githubusercontent.com/1921992/143787537-28d372e8-8cbf-418f-b91e-633cb9dd76a3.mp4

####  Links
- Definition: https://support.orcid.org/hc/en-us/articles/360006971333-Peer-Review
- API : https://api.orcid.org/v3.0/#!/Development_Member_API_v3.0/viewPeerReviewv3
- SANDBOX API https://api.sandbox.orcid.org/v3.0/#!/Development_Member_API_v3.0/createPeerReviewv3
- Peer Review Orcid https://github.com/ORCID/ORCID-Source/blob/master/orcid-api-web/tutorial/peer-review.md
- Niso group https://www.niso.org/standards-committees/peer-review-taxonomy
- marc codes  https://www.loc.gov/marc/countries/countries_name.html

#### Orcid Review display

![Reviewer-Info](https://support.orcid.org/hc/article_attachments/1500000536682/1.png)

-  In user profiles,  peer-review will be visible only when the user has enabled it. [ref](https://support.orcid.org/hc/en-us/articles/360006897614)

#####  a.  Information about the reviewer

1.    Role (required): The individual’s role in the review process, e.g. chair, editor, member, organizer, **reviewer**  :ok: 

2.    Identifier (required): The reviewer’s **ORCID iD**
  full orcid URL including https :ok:

##### b. Information about the organizer

-    Convening organization (required): This describes the organization which organized the review - a **_journal publisher_**, **_conference organizer_**, funding agency, faculty, etc.

3.  We can use the Publisher name under Settings- > Journal -> masterhead -> publisher  :question: 

 Location

4.   City (required): The city where the organizer is based
   -   Region: The region where the organizer is based
  -   Country (required): The country where the organizer is based

 If I am correct, the only location where the  journal address is  default maintained is  under principal contact. There also we have the mailing address. This can be a little tricky  to parse, if the  journal managers do not provide  it correctly.  _Country_ is straight-forward, but the city can be not easy to find.

Another possibility is to  get the location from the issn. Haven't explored it whether they have an API  or does it make sense ?
e.g. https://portal.issn.org/resource/ISSN/0006-1387  :question: 

 5.   Identifier (required): The persistent identifier for the organization

ISSN of the journal or ROR id  of the press /  hosting organization :question:  

##### c. Information about the review

6.    Group (required): An identifier used to group together the reviews on the ORCID record; it describes the group of which the review is part. This could be the name of a journal (Journal of Scientific Investigations) or an organization (Scholarly Publisher, State University)

 User -> affiliation  :question: 

 7.   Type (required): The type of review activity, e.g., a review, evaluation
 
Review :ok: 

 8.   Date (required): When the review was completed. This can be broad (2008) or specific 
 
Reveiw data :ok: 
 
 9.   Review container name: The name of main object of which the review is part, e.g. journal, conference, grant review panel, etc.

journal name :ok: 

10.    Review identifier (required): A unique resolvable identifier provided by the source for the review itself. This is used to prevent duplication of review activity. Reviews can have more than one identifier, and multiple reviews with the same identifier will group together

Do we have a reviewer URL  for the front-end  through a plugin may be :question: 

References:

This plugin sends reviewer id, submission-id,data and (due and submission)   to reveiwercredits.com

https://www.reviewercredits.com/integrations-for-journals-and-manuscript-platforms/

  
Related to 10 

11,  Review URL: A link to the representation of the review online

##### d. Information about the review subject

-    Review subject name: The title of the item reviewed
-    Review subject type: The type of item that was reviewed, e.g. article, grant, monograph
-    Review subject identifier: A unique resolvable identifier for the reviewed item, e.g. a DOI
-    Review subject URL: A link to the reviewed item online

OJS supports all :ok:

#### References

- https://support.orcid.org/hc/en-us/articles/360006971333-Peer-Review

##### TODO

- [x]  Check the review round
- [x]   Check  visibility
- [x]  Sending emails
- [x]  Update with put code
- [x]  Deleting  submission
- [x]  Country codes as plugin settings
- [ ]  

#### Related tickets
-  https://github.com/pkp/pkp-lib/issues/7406
-  https://github.com/pkp/pkp-lib/issues/7405
- https://github.com/pkp/pkp-lib/issues/7404

**Comment by withanage** [comment]
Hi @asmecher,


I have gone through the requirements from orcid.org of adding o reviewer information for the orcidPlugin.


Most of the  requirements seem to be supported directly from OJS, but for the points 4 and 10, I think we have to think for a solution,  what is the best possiblie solution. i am not sure , if 4 or 10 was already adressed by any plugins ?

**Comment by withanage** [comment]
Hi @NateWr 
> Can you describe the reviewer mapping table in more detail? I'm not sure what I'm looking at there.


I have taken the out mapping part here for disucussion.  My suggestion  was  that may be the numbered metadata fields can be published openly for the various reviewer types without disclosing the anonymity. 

#### Mapping

| Identity transparency  | Accept Submission | Revisions Required  | Resubmit for Review  | Resubmit Elsewhere | Decline Submission | See Comments |   
| --- |  ---- |  --- |  ---- | --- |  ---- | --- |
| Anonymous Reviewer/Anonymous Author (Double anonymized) | 5,7 |5,7 |5,7 |5,7 |5,7 | x |
| Anonymous Reviewer/Disclosed Author (Single anonymized)	 | 5,7 | 5,7 |5,7 |5,7 |5,7 | x |  
| Open (All identities visible)| 1,2,3,5,6,7 | 1,2,3,5,6,7 | 1,2,3,5,6,7 | 1,2,3,5,6,7 | 1,2,3,5,6,7 |  x |

####  Metadata
| Information | Orcid Field |
| --- |  ---- |
| 1. Date of submission | created-date |
| 2. Date of acceptance  (review)|  review-completion-date|
| 3. Date of publication  | created-date |
| 4. Number of reviewer reports submitted in first round |  :x: | 
| 5. Number of revision rounds |  source-name |
| 6. Article Group (ISSN) | review-group-id |
| 7. Article URL   | review-url |

**Comment by NateWr** [comment]
@withanage What do the recommendation columns mean in the table? Does it matter what decision the reviewer takes?

**Comment by withanage** [comment]
> @withanage What do the recommendation columns mean in the table? Does it matter what decision the reviewer takes?

@NateWr : actually other than the comments , it does not matter, I added only for  completeness. For the comments,  I was not 100% sure ,cause the reviewer may opt for not reviewing by giving a reason as a comment. I think in this case, it may be better as you suggested  https://github.com/pkp/orcidProfile/issues/181#issuecomment-953651783  to   trigger the orcid API communication, at the moment when an editor reads review and confirms it.

**Comment by NateWr** [comment]
Yeah, I think that reviewers often use See Comments even when they include a review, but don't want to choose a pre-selected recommendation. I think we should expect to send it on to ORCID unless the editor does something.

In terms of what data to send to ORCID, I feel like we should probably send all the data in all cases. It should be up to ORCID to decide what to show depending on whether the review is anonymous or not. For example, they'll still need the date in order to show the year in which a review occurred, as can be seen in this example: https://orcid.org/0000-0001-7795-4652

Ultimately, the anonymity is about the article that was reviewed and the precise date. So maybe the metadata table should look like this:

| Information | Orcid Field | Anonymous | Open |
| --- |  --- | --- | --- |
| 1. Date of submission | created-date | YYYY | YYYY-MM-DD |
| 2. Date of acceptance  (review)|  review-completion-date | YYYY | YYYY-MM-DD |
| 3. Date of publication  | created-date | YYYY | YYYY-MM-DD |
| 7. Article URL   | review-url | :x: | :heavy_check_mark: |

**Comment by withanage** [comment]
@NateWr  thanks for the abstraction. Yes, I missed the review-url totally and  I will take i the above table as the specification.

**Comment by withanage** [comment]
@NateWr 

> How does ORCID handle disputes on its end? Or situations where the depositing authority is no longer available to curate the depositing data?

Quote:

>> We do not provide specific instructions on how to proceed if the article is removed. Other than that, the member organization could delete the peer review if they have permission to do so (/activities/update). [And at the following link you can find our Dispute Procedure]( https://info.orcid.org/dispute-procedures/.)


In  a quick overview, we could delete them. I will have a look into it in more detail and come with a proposal.

**Comment by NateWr** [comment]
> we could automatically delete them, if the submission is removed. I will have a look into it in more detail and come with a proposal.

I suspect it's going to be very rare that a submission will go through reviews but then those reviews should be withdrawn from orcid. I know I raised this issue, but on second thought, I think we can leave this to ORCID to sort out. People delete submissions for lots of reasons in OJS, and most of the time the review credit should remain with ORCID.

**Comment by klausru** [comment]
Dear @withanage 
can you confirm that the delivery of Reviewer Credits towards ORCID really works for ORCID Members in production mode? From reading the above I wasn't sure if this feature is mature and out of alpha status.
In addition to that: We are planning to become member of ORCID. Is there any script or trigger to deliver back issues / reviewer data to ORCID from past reviews? I wouldn't want unpublish - republish each and every article.
Thank you so much and all the best

**Comment by withanage** [comment]
Hi @klausru ,
> can you confirm that the delivery of Reviewer Credits towards ORCID really works for ORCID Members in production mode? From reading the above I wasn't sure if this feature is mature and out of alpha status.

The functionality  can be used for production purposes.

> In addition to that: We are planning to become member of ORCID. Is there any script or trigger to deliver back issues / reviewer data to ORCID from past reviews? I wouldn't want unpublish - republish each and every article.

no, unfortunately there isn't a script for re-publish in the current version and is also not planned currently.
